// The emoji the console's own picker offers, so marking a session never needs the
// OS emoji keyboard. Every entry is exactly one RGI emoji sequence — the shape the
// daemon validates a mark against — paired with a short lowercase search string of
// a name and a synonym or two. The work group comes first because that is what a
// session gets tagged with; the rest follows the usual keyboard's order.
//
// emoji-list.test.js holds the list to its promises: one RGI emoji each, no
// duplicates, a non-empty lowercase search string each.
export const EMOJI = [
  // Work: the ones worth reaching for when tagging a session.
  ['🔥', 'fire hot burning'],
  ['🚀', 'rocket launch ship'],
  ['🎯', 'target goal focus'],
  ['🐛', 'bug defect broken'],
  ['🔧', 'wrench fix tool'],
  ['🛠️', 'tools hammer wrench build'],
  ['🧪', 'test experiment lab'],
  ['🧹', 'broom cleanup sweep tidy'],
  ['🔍', 'search magnify find investigate'],
  ['📦', 'package box release bundle'],
  ['🚢', 'ship deploy boat'],
  ['🧭', 'compass navigate direction'],
  ['🧱', 'brick wall block'],
  ['🪄', 'magic wand trick'],
  ['🧠', 'brain think smart'],
  ['⚡', 'zap lightning fast power'],
  ['🛰️', 'satellite orbit telemetry'],
  ['🧵', 'thread spool sewing'],
  ['🧯', 'extinguisher fire safety'],
  ['🚧', 'construction barrier wip'],
  ['🏗️', 'crane building construction'],
  ['🔒', 'lock secure closed security'],
  ['🔑', 'key access unlock secret'],
  ['🧩', 'puzzle piece integration'],
  ['📌', 'pin pushpin place'],
  ['📎', 'paperclip attach'],
  ['📝', 'memo note write draft'],
  ['📊', 'bar chart stats data'],
  ['📈', 'chart up growth increase'],
  ['📉', 'chart down decline drop'],
  ['🗂️', 'dividers files folders index'],
  ['🗒️', 'notepad spiral notes'],
  ['💾', 'floppy save disk'],
  ['🖥️', 'desktop computer screen'],
  ['📱', 'phone mobile device'],
  ['🌐', 'globe web internet network'],
  ['🔔', 'bell notify alert ring'],
  ['⏰', 'alarm clock time wake'],
  ['⏳', 'hourglass waiting time slow'],
  ['✅', 'check done ok pass'],
  ['❌', 'cross no fail wrong'],
  ['⚠️', 'warning caution careful'],
  ['❗', 'exclamation important urgent'],
  ['❓', 'question unknown ask'],
  ['💡', 'bulb idea light insight'],
  ['🎉', 'party tada celebrate'],
  ['🏁', 'checkered flag finish race'],
  ['🏆', 'trophy win award'],
  ['🥇', 'gold medal first place'],
  ['🎲', 'dice random game chance'],
  ['🎨', 'art palette design paint'],
  ['🎬', 'clapper film action movie'],
  ['🎧', 'headphones audio music listen'],
  ['📣', 'megaphone announce shout'],
  ['👀', 'eyes look watch review'],
  ['🤖', 'robot bot agent'],
  ['👻', 'ghost spooky haunted'],
  ['💀', 'skull dead fatal'],
  ['☠️', 'skull crossbones danger poison'],
  ['🧟', 'zombie undead stuck'],
  ['🧨', 'dynamite explosive fuse'],
  ['💥', 'boom collision explosion crash'],
  ['💫', 'dizzy sparkle spin'],
  ['⭐', 'star favorite'],
  ['🌟', 'glowing star shine special'],
  ['✨', 'sparkles shine new magic'],
  ['🌈', 'rainbow colors pride'],
  ['☀️', 'sun sunny day'],
  ['🌙', 'moon night crescent'],
  ['☁️', 'cloud sky'],
  ['🌧️', 'rain cloud wet'],
  ['❄️', 'snowflake cold freeze'],
  ['🌊', 'wave water ocean flood'],
  // Faces.
  ['😀', 'grin happy smile'],
  ['😅', 'sweat smile nervous relief'],
  ['😂', 'joy laugh tears'],
  ['🙃', 'upside down silly irony'],
  ['😉', 'wink'],
  ['😊', 'blush smile warm'],
  ['😍', 'heart eyes love adore'],
  ['😎', 'cool sunglasses smooth'],
  ['🤔', 'thinking hmm consider'],
  ['🤯', 'mind blown exploding head'],
  ['😱', 'scream shock fear'],
  ['😴', 'sleep sleeping zzz idle'],
  ['🥳', 'party face celebrate'],
  ['🤠', 'cowboy hat yeehaw'],
  ['🫠', 'melting face melt overwhelmed'],
  ['😬', 'grimace awkward yikes'],
  ['🤢', 'nauseated sick gross'],
  ['🤡', 'clown joke fool'],
  ['👽', 'alien extraterrestrial'],
  ['🥸', 'disguise glasses incognito'],
  ['🫡', 'salute yes sir acknowledged'],
  ['😤', 'huff triumph steam determined'],
  ['😭', 'sob cry bawling'],
  ['😡', 'rage angry mad'],
  ['🤩', 'star struck excited amazed'],
  // Hands and people.
  ['👍', 'thumbs up yes approve'],
  ['👎', 'thumbs down no reject'],
  ['👋', 'wave hello bye'],
  ['🙏', 'pray thanks please'],
  ['💪', 'muscle strong flex'],
  ['🫶', 'heart hands love care'],
  ['🤝', 'handshake deal agree'],
  ['✌️', 'victory peace two'],
  ['🤞', 'fingers crossed luck hope'],
  ['👏', 'clap applause bravo'],
  ['🤙', 'call me shaka hang loose'],
  ['🧑‍💻', 'technologist developer coder'],
  ['👩‍🚀', 'astronaut space explorer'],
  ['🧑‍🔬', 'scientist lab research'],
  ['🧑‍🍳', 'cook chef kitchen'],
  // Animals.
  ['🐶', 'dog puppy woof'],
  ['🐱', 'cat kitty meow'],
  ['🦊', 'fox firefox sly'],
  ['🐻', 'bear'],
  ['🐼', 'panda'],
  ['🐨', 'koala'],
  ['🦁', 'lion brave'],
  ['🐸', 'frog toad'],
  ['🐙', 'octopus tentacles'],
  ['🦄', 'unicorn magic rare'],
  ['🐢', 'turtle slow tortoise'],
  ['🦀', 'crab rust pinch'],
  ['🐝', 'bee busy buzz'],
  ['🦋', 'butterfly change'],
  ['🐌', 'snail slow crawl'],
  ['🦉', 'owl night wise'],
  ['🐧', 'penguin linux'],
  ['🦖', 'dinosaur trex rex'],
  ['🐍', 'snake python'],
  ['🦈', 'shark fin'],
  ['🐳', 'whale docker spout'],
  // Food and drink.
  ['🍕', 'pizza slice'],
  ['🍔', 'burger hamburger'],
  ['🌮', 'taco'],
  ['🍣', 'sushi fish rice'],
  ['🍩', 'donut doughnut'],
  ['🍪', 'cookie biscuit'],
  ['🎂', 'cake birthday'],
  ['🍎', 'apple red fruit'],
  ['🍋', 'lemon sour citrus'],
  ['🥑', 'avocado'],
  ['🌶️', 'chili pepper spicy hot'],
  ['☕', 'coffee tea mug'],
  ['🍺', 'beer pint cheers'],
  ['🍷', 'wine glass'],
  ['🧊', 'ice cube cold frozen'],
  // Travel and objects.
  ['🚗', 'car drive auto'],
  ['🚲', 'bike bicycle cycle'],
  ['✈️', 'plane flight airplane'],
  ['🚁', 'helicopter chopper'],
  ['🛸', 'ufo flying saucer'],
  ['⛵', 'sailboat sailing yacht'],
  ['🏠', 'house home local'],
  ['🏰', 'castle fortress'],
  ['🗼', 'tower landmark'],
  ['🎪', 'circus tent show'],
  ['⛺', 'tent camping outdoors'],
  ['🎁', 'gift present box'],
  ['🎈', 'balloon float'],
  ['📷', 'camera photo snapshot'],
  ['🔭', 'telescope stars far'],
  ['🔬', 'microscope detail close'],
  ['💎', 'gem diamond precious'],
  ['🧲', 'magnet attract pull'],
  ['🪙', 'coin token'],
  ['💰', 'money bag cash cost'],
  ['🧸', 'teddy bear toy plush'],
  ['🚂', 'train locomotive rail'],
  ['🛏️', 'bed sleep rest'],
  // Symbols and flags.
  ['❤️', 'red heart love'],
  ['🧡', 'orange heart'],
  ['💛', 'yellow heart'],
  ['💚', 'green heart'],
  ['💙', 'blue heart'],
  ['💜', 'purple heart'],
  ['🖤', 'black heart'],
  ['🤍', 'white heart'],
  ['💔', 'broken heart split'],
  ['♻️', 'recycle reuse loop'],
  ['☮️', 'peace sign'],
  ['⚛️', 'atom science physics'],
  ['♾️', 'infinity endless forever'],
  ['🔺', 'red triangle up'],
  ['🔻', 'red triangle down'],
  ['🔷', 'blue diamond shape'],
  ['🔶', 'orange diamond shape'],
  ['🟥', 'red square'],
  ['🟧', 'orange square'],
  ['🟨', 'yellow square'],
  ['🟩', 'green square'],
  ['🟦', 'blue square'],
  ['🟪', 'purple square'],
  ['⬛', 'black square'],
  ['⬜', 'white square'],
  ['🏴‍☠️', 'pirate flag jolly roger'],
  ['🏳️‍🌈', 'rainbow flag pride'],
  ['🚩', 'red flag triangular'],
];
